### ISSUE TITLE
investigate synchronization between different instances

### ISSUE THREAD

**Issue by KonradHoeffner** [annosaxfdm/ols#1]
Ausschnitt Projektantrag:

> Die Ontologie wird in einem Terminologierservice verwaltet, der sich mit denen der NFDI synchronisiert.

https://terminology.nfdi4ing.de/ts4ing/index

**Comment by KonradHoeffner** [comment]
> Die Synchronisationskomponente ist nicht genauer spezifiziert, d.h. wir können es uns selbst überlegen. Ich stelle es mir so vor, dass man in einer OLS-Instanz (A) eine andere OLS-Instanz (B) als Quelle angeben kann und die Ontologien aus B werden in A importiert (falls nicht bereits vorhanden). Man könnte es regelmäßig automatisiert machen oder den Austausch manuell anstoßen. Wenn man für beide OLS-Instanzen Schreibrechte hat, kann man das dann in beide Richtungen synchronisieren.

**Comment by KonradHoeffner** [comment]
Asked for official synchronization support by EBISPOT/OLS at <https://github.com/EBISPOT/OLS/issues/589>, response:

> Nothing like this exists at the moment. If I were to implement it I would perhaps think about modifying the config importer to import the configuration from the other instance, but I'm not sure how easy this would be.

**Comment by KonradHoeffner** [comment]
Ich habe bei der NFDI folgende Terminologieservices gefunden, die alle auf OLS aufbauen:

|Name|Inhalt|URL|
|-------|-------|-------|
|NFDI4ing |Engineering|https://terminology.nfdi4ing.de|
|NFDI4Chem|Chemie|https://terminology.nfdi4chem.de|
|TIB (Oberserver der NFDI?)|architecture, chemistry, computer science, mathematics, physics,... |https://service.tib.eu/ts4tib/index|

**Comment by KonradHoeffner** [comment]
Anscheinend werden die Ontologien alle über [OBO PURLs](https://github.com/OBOFoundry/purl.obolibrary.org/) geladen.
Dort erstellt man eine neue [Issue mit einem Pull Request für eine neue Konfigurationsdatei](https://github.com/OBOFoundry/purl.obolibrary.org#adding-and-updating-purls).
Dort verweist man über einen GitHub Link auf eine Ontologie, z.B.:

    products:
    - aism.owl: https://raw.githubusercontent.com/insect-morphology/aism/master/aism.owl

Dies erzeugt dann einen Link auf den Inhalt von <https://github.com/insect-morphology/aism/blob/master/aism.owl>.


In unseren Fall könnte eine Konfigurationsdatei so aussehen:

## anno.yml

```yml
# PURL configuration for http://purl.obolibrary.org/obo/agro

idspace: ANNO
base_url: /obo/anno

products:
- anno.owl: https://raw.githubusercontent.com/AgriculturalSemantics/agro/master/agro.owl
- anno.obo: https://raw.githubusercontent.com/AgriculturalSemantics/agro/master/agro.obo

term_browser: ontobee
example_terms:
- ...

entries:
- exact: /mappings/...-mapping.tsv
  replacement: http://purl.obolibrary.org/obo/anno/mappings/...-mapping.tsv

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/annosaxfdm/ontology/v

- prefix: /mappings/
  replacement: https://raw.githubusercontent.com/annosaxfdm/ontology/master/mappings/

- prefix: /subsets/
  replacement: https://raw.githubusercontent.com/annosaxfdm/ontology/master/subsets/

- prefix: /imports/
  replacement: https://raw.githubusercontent.com/annosaxfdm/ontology/master/imports/
```
